### ISSUE TITLE
R-T3.4-8: The defect-prediction tool must provide filters to decide which predefined defects to find

### ISSUE THREAD

**Issue by dardin88** [radon-h2020/radon-defect-prediction-plugin#5]
ID | R-T3.4-8
-- | --
Section | WP3: Methodology and Quality Assurance Requirements
Type | USABILITY
User Story | As an Operations Engineer I want to be able to find for specific defects
Requirement | The defect-prediction tool must provide filters to decide which predefined defects to find
Extended Description | The user should be able to filter which predefined defects are to be found
Priority | Must have
Affected Tools | DEFECT_PRED_TOOL
Means of Verification | Direct implementation on IDE, feature checklist, case-study
Dependency |  R-T3.4-1 https://github.com/radon-h2020/radon-defect-prediction-api/issues/2 (could use) <br> R-T3.4-2 https://github.com/radon-h2020/radon-defect-prediction-api/issues/4 (could use) <br> R-T3.4-3 https://github.com/radon-h2020/radon-defect-prediction-api/issues/3 (could use)

**Comment by stefanodallapalma** [comment]
@gcasale 
Status: TODO

**Comment by stefanodallapalma** [comment]
At this point of the project, I am noticing that partners are more interested to have a user-friendly tool without cumbersome information to deal with. Rather than allowing the user to decide which predefined defects to find, I propose to change this requirement so to provide the type(s) of defect(s) found. That is, replacing the prediction "script might be failure-prone" with the actual defect type(s), e.g., 'script might have service- and configuration data-related defects". Eventually, this change is ready for deployment.

**Comment by gcasale** [comment]
OK for me
